name: Node.js CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Create report directory
      run: mkdir -p mochawesome-report/api

    - name: Start Express Server in background
      run: |
        node src/app.js &
        sleep 3 # Aguarda o servidor inicializar na porta 3000

    - name: Run k6 performance test
      uses: grafana/k6-action@v0.3.1
      with:
        filename: tests/performance/load.test.js

    - name: Run all functional tests (Unit + API + Smoke)
      run: npm test

    - name: Prepare Mochawesome Report for GitHub Pages
      if: always()
      run: |
        # Renomeia o relatório funcional para index.html para ser a página principal
        mv mochawesome-report/api/api-tests.html mochawesome-report/api/index.html

    - name: Deploy Test Reports to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./mochawesome-report/api
