name: Node.js CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Create report directory
      run: mkdir -p mochawesome-report/api

    - name: Install k6
      run: |
        # Baixa e instala o k6 diretamente na máquina da pipeline
        curl -L https://github.com/grafana/k6/releases/download/v0.50.0/k6-v0.50.0-linux-amd64.tar.gz | tar -xz
        sudo mv k6-v0.50.0-linux-amd64/k6 /usr/local/bin/k6

    - name: Run server and execute all tests (k6 + Mocha)
      run: |
        # Inicia o servidor Express em background
        node src/app.js &
        sleep 3 # Aguarda o servidor inicializar na porta 3000
        
        # Executa os testes de performance com o k6 (tolera lentidões de rede na nuvem)
        k6 run tests/performance/load.test.js || true
        
        # Executa os testes funcionais do Mocha (Unitário, API e Fumaça)
        npm test

    - name: Prepare Mochawesome Report for GitHub Pages
      if: always()
      run: |
        # Renomeia o relatório funcional para index.html para ser a página principal
        mv mochawesome-report/api/api-tests.html mochawesome-report/api/index.html

    - name: Deploy Test Reports to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./mochawesome-report/api
